<!-- Main (Home) section -->
<section class="section" id="head">
	<div class="container">

		<div class="row">
			<div class="col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1 text-center">	

			
				<h2 class="subtitle"><?php echo $this->translate('Currency Fair Test'); ?></h2>

				
				
				 <p> <a href="<?php echo $this->url('application/faircalc') ?>" class="btn btn-default btn-lg"><?php echo $this->translate('Fair calc') ?></a></p>

	
			</div> <!-- /col -->
		</div> <!-- /row -->
	
	</div>
</section>