<!-- Main (Home) section -->
<section class="section" id="head">
	<div class="container">

		<div class="row">
			<div class="col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1 text-center">	

			
				<h1 class="title">IMO4.COM</h1>
				<h2 class="subtitle"><?php echo $this->translate('Pricing'); ?></h2>

                
           <?php echo $this->translate('For each ad with 3 months online : ')?>
          
     
           <?php echo $this->translate('5.00 euros taxes included')?>
           
 	
				
	
			</div> <!-- /col -->
                        

		</div> <!-- /row -->
	
	</div>
</section>